name: visual-query-builder
display_name: Visual SQL Query Builder
description: A modern visual interface for building SQL queries with Unity Catalog integration

env:
  - name: 'NODE_ENV'
    value: 'production'
  - name: 'LOG_LEVEL'
    value: 'info'
  - name: 'FEATURE_ALLOW_NO_DBRX'
    value: '0'
  - name: 'DATABRICKS_HOST'
    value: 'dbc-fe7b006c-c783.cloud.databricks.com'
  - name: 'DATABRICKS_WORKSPACE_ID'
    value: '1696917271484752'
  - name: 'DATABRICKS_APP_PORT'
    value: '8000'
  - name: 'DATABRICKS_WAREHOUSE_ID'
    value: 'a274378bae39d2e1'

# Required permissions for Unity Catalog access
permissions:
  - permission: CAN_USE_CATALOG
  - permission: CAN_USE_SCHEMA
  - permission: CAN_SELECT
  - permission: CAN_USE_WAREHOUSE
  - permission: CAN_READ_CATALOG
  - permission: CAN_READ_SCHEMA
  - permission: CAN_READ_TABLE
  - permission: CAN_READ_COLUMN

# App configuration
config:
  runtime: nodejs18
  timeout: 300s
  auth:
    type: workspace
