name: visual-query-builder
display_name: Visual SQL Query Builder
description: A modern visual interface for building SQL queries with Unity Catalog integration

command: ["npm", "run", "start"]

env:
  - name: 'NODE_ENV'
    value: 'production'
  - name: 'LOG_LEVEL'
    value: 'info'
  - name: 'FEATURE_ALLOW_NO_DBRX'
    value: '0'  # Changed to 0 to enforce proper environment
  - name: "DATABRICKS_WAREHOUSE_ID"
    value: "a274378bae39d2e1"
  - name: "DATABRICKS_SERVER_HOSTNAME"
    value: "dbc-fe7b006c-c783.cloud.databricks.com"

# Required permissions for Unity Catalog access
permissions:
  - permission: CAN_USE_CATALOG
  - permission: CAN_USE_SCHEMA
  - permission: CAN_SELECT
  - permission: CAN_USE_WAREHOUSE
  - permission: CAN_READ_CATALOG
  - permission: CAN_READ_SCHEMA
  - permission: CAN_READ_TABLE
  - permission: CAN_READ_COLUMN

# App configuration
config:
  # Ensure the app runs in the proper Databricks Apps context
  runtime: nodejs18
  # Set appropriate timeout for SQL queries
  timeout: 300s
  # Enable proper authentication context
  auth:
    type: workspace
    oauth_scopes:
      - sql

