name: Deploy to Databricks

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Databricks CLI
      run: |
        pip install databricks-cli>=0.219.0
        
    - name: Deploy to Databricks
      env:
        DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
        DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        DATABRICKS_REPO_PATH: ${{ secrets.DATABRICKS_REPO_PATH }}
        APP_NAME: ${{ secrets.APP_NAME }}
        BRANCH: ${{ secrets.BRANCH || 'main' }}
      run: |
        make deploy
